# Generated by Django 6.0.6 on 2026-07-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
