# Generated by Django 4.2.11 on 2026-07-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_orderitem_price_orderitem_menu_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8),
        ),
    ]
