# Generated by Django 6.0.6 on 2026-07-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
